Modellimplementierung
FlorianAlbert/Projekt-Apollon pull request #97
Opened 2021-04-23 19:18 UTC by Rustemi-A

2021-04-24 19:56 UTC, etienneZink commented on application/Apollon.Mud/Server.Model.Test/Dungeon/Avatar/InventoryTests.cs
> +        public void Add_WeightSumOverMaximum_Fail()
Theoretisch keine Prüfung der Sum() Funktionalität sondern nur davon, dass 0 + 150 > 100. Wäre ein Testfall mit einem nicht leeren Inventar sinnvoll?

2021-04-24 20:00 UTC, etienneZink commented on application/Apollon.Mud/Server.Model/Implementations/Dungeon/Npc/Npc.cs
> +        /** TODO: Nicht vergessen zu löschen oder zu verschieben
Kann gelöscht werden

2021-04-24 20:02 UTC, etienneZink commented on application/Apollon.Mud/Server.Model/Implementations/Dungeon/Requestable/Requestable.cs
> +        public string Message { get; set; }
Wäre es vielleicht sinnvoll ein Pattern zu hinterlegen als eine ganze Message? SpecialActions sollten auch über ein oder zwei Keywords ausgelöst werden?

2021-04-24 20:03 UTC, etienneZink commented on application/Apollon.Mud/Server.Model/Implementations/Dungeon/Room/Room.cs
> +            description = Description;
Fehler im Code

2021-04-24 20:04 UTC, etienneZink commented on application/Apollon.Mud/Server.Model/Implementations/Dungeon/Requestable/Requestable.cs
> +            message = Message;
Fehler im Code

2021-04-25 12:54 UTC, etienneZink requested changes
Few changes needed.

2021-04-25 15:18 UTC, FlorianAlbert commented on application/Apollon.Mud/Server.Model.Test/Dungeon/Avatar/InventoryTests.cs
> +        public void Add_WeightSumOverMaximum_Fail()
Erledigt

2021-04-25 15:18 UTC, FlorianAlbert commented on application/Apollon.Mud/Server.Model/Implementations/Dungeon/Npc/Npc.cs
> +        /** TODO: Nicht vergessen zu löschen oder zu verschieben
Ist gelöscht

2021-04-25 15:19 UTC, FlorianAlbert commented on application/Apollon.Mud/Server.Model/Implementations/Dungeon/Requestable/Requestable.cs
> +        public string Message { get; set; }
Ersetzt durch Regex Pattern und Pattern Message für Player

2021-04-25 15:19 UTC, FlorianAlbert commented on application/Apollon.Mud/Server.Model/Implementations/Dungeon/Room/Room.cs
> +            description = Description;
Verbessert

2021-04-25 15:19 UTC, FlorianAlbert commented on application/Apollon.Mud/Server.Model/Implementations/Dungeon/Requestable/Requestable.cs
> +            message = Message;
Verbessert

2021-04-26 14:30 UTC, etienneZink approved these changes

2021-04-26 14:36 UTC, etienneZink submitted a review, later dismissed

2021-04-26 14:40 UTC, etienneZink approved these changes

2021-04-26 14:41 UTC, merged